```{r ortab, cache=cacheon}

ormy <- function(event, modvarsmy, data, modname, weightsmy = c("weight_rasi", "weight_mra")) {
  out <- list(
    data.frame(matrix(NA, ncol = 9, nrow = 4, 1)),
    data.frame(matrix(NA, ncol = 9, nrow = 4, 1))
  )
  names(out) <- modvarsmy[1:2]

  for (i in 1:2) {
    out[[i]][1, 1] <- modname

    colnames(out[[i]]) <- c(
      "Outcome/Subgroup", "Model", "No", "Yes",
      "p-value", "logor", "loglci", "loguci", "modname"
    )

    ns <- data %>%
      group_by(!!sym(modvarsmy[i])) %>%
      count(!!sym(event)) %>%
      mutate(
        p = n / sum(n),
        np = paste0(n, " (", dF(p * 100, dig = 2), "%)")
      ) %>%
      ungroup() %>%
      filter(!!sym(event) == "Yes")

    out[[i]][1, 2] <- "n (%) event"
    out[[i]][1, 3:4] <- ns %>% pull(np)


    # Crude
    mod <- glm(formula(paste(event, " == 'Yes' ~ ", modvarsmy[i])),
      data = data,
      family = binomial(link = "logit")
    )
    smod <- summary(mod)

    out[[i]][2, 2] <- "Crude OR (95% CI)"
    out[[i]][2, 3:5] <- cbind(
      "ref",
      paste0(
        dF(exp(smod$coefficients[2, 1]), dig = 2),
        " (", dF(exp(smod$coefficients[2, 1] - global_z05 * smod$coefficients[2, 2]), dig = 2),
        "-", dF(exp(smod$coefficients[2, 1] + global_z05 * smod$coefficients[2, 2]), dig = 2), ")"
      ),
      dF(smod$coefficients[2, 4], dig = 3, p = TRUE)
    )


    # Adj pS IPW

    mod <- glm(formula(paste(event, " == 'Yes' ~ ", paste(modvarsmy, collapse = " + "))),
      data = data,
      family = binomial(link = "logit"),
      weights = data %>% pull(!!sym(weightsmy[i]))
    )

    smod <- jtools::get_robust_se(mod, type = "HC0")

    out[[i]][4, 2] <- "Adj IPW OR (95% CI)"
    out[[i]][4, 3:5] <- cbind(
      "ref",
      paste0(
        dF(exp(smod$coefs[i + 1, 1]), dig = 2),
        " (", dF(exp(smod$coefs[i + 1, 1] - global_z05 * smod$coefs[i + 1, 2]), dig = 2),
        "-", dF(exp(smod$coefs[i + 1, 1] + global_z05 * smod$coefs[i + 1, 2]), dig = 2), ")"
      ),
      dF(smod$coefs[i + 1, 4], dig = 3, p = TRUE)
    )

    # for forestplot
    out[[i]][4, 6] <- smod$coefs[i + 1, 1]
    out[[i]][4, 7] <- smod$coefs[i + 1, 1] - global_z05 * smod$coefs[i + 1, 2]
    out[[i]][4, 8] <- smod$coefs[i + 1, 1] + global_z05 * smod$coefs[i + 1, 2]
    out[[i]][4, 9] <- modname
  }

  # Adj
  mod <- glm(formula(paste(event, " == 'Yes' ~ ", paste(modvarsmy, collapse = " + "))),
    data = data,
    family = binomial(link = "logit")
  )

  smod <- summary(mod)


  for (i in 1:2) {
    out[[i]][3, 2] <- "Adj OR (95% CI)"
    out[[i]][3, 3:5] <- cbind(
      "ref",
      paste0(
        dF(exp(smod$coefficients[i + 1, 1]), dig = 2),
        " (", dF(exp(smod$coefficients[i + 1, 1] - global_z05 * smod$coefficients[i + 1, 2]), dig = 2),
        "-", dF(exp(smod$coefficients[i + 1, 1] + global_z05 * smod$coefficients[i + 1, 2]), dig = 2), ")"
      ),
      dF(smod$coefficients[i + 1, 4], dig = 3, p = TRUE)
    )
  }
  return(out)
}

out11 <- ormy(
  event = "sos_covidconfirmed",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns),
  data = pop,
  modname = "All"
)
out13 <- ormy(
  event = "sos_covidconfirmed",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_hf"]),
  data = pop %>% filter(sos_com_hf == "Yes"),
  modname = "HF"
)
out14 <- ormy(
  event = "sos_covidconfirmed",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_hypertension"]),
  data = pop %>% filter(sos_com_hypertension == "Yes"),
  modname = "Hypertension"
)
out15 <- ormy(
  event = "sos_covidconfirmed",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_renal"]),
  data = pop %>% filter(sos_com_renal == "Yes"),
  modname = "Kidney disease"
)
out16 <- ormy(
  event = "sos_covidconfirmed",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_ihd"]),
  data = pop %>% filter(sos_com_ihd == "Yes"),
  modname = "IHD"
)
out17 <- ormy(
  event = "sos_covidconfirmed",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_diabetes"]),
  data = pop %>% filter(sos_com_diabetes == "Yes"),
  modname = "Diabetes"
)
out18 <- ormy(
  event = "sos_covidconfirmed",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "scb_region_stockholm"]),
  data = pop %>% filter(scb_region_stockholm == "Yes"),
  modname = "Stockholm"
)
out19 <- ormy(
  event = "sos_out_hospbleed",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns),
  data = pop,
  modname = "Negative control - Bleed"
)
out110 <- ormy(
  event = "sos_out_hospcancer",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns),
  data = pop,
  modname = "Negative control - Cancer"
)
out111 <- ormy(
  event = "sos_out_hospliver",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns),
  data = pop,
  modname = "Negative control - Liver"
)

outall <- cbind(
  outrasi <- rbind(
    out11[["sos_ddr_rasi"]], out13[["sos_ddr_rasi"]], out14[["sos_ddr_rasi"]],
    out15[["sos_ddr_rasi"]], out16[["sos_ddr_rasi"]], out17[["sos_ddr_rasi"]],
    out18[["sos_ddr_rasi"]], out19[["sos_ddr_rasi"]], out110[["sos_ddr_rasi"]],
    out111[["sos_ddr_rasi"]]
  ),
  outmra <- rbind(
    out11[["sos_ddr_mra"]], out13[["sos_ddr_mra"]], out14[["sos_ddr_mra"]],
    out15[["sos_ddr_mra"]], out16[["sos_ddr_mra"]], out17[["sos_ddr_mra"]],
    out18[["sos_ddr_mra"]], out19[["sos_ddr_mra"]], out110[["sos_ddr_mra"]],
    out111[["sos_ddr_mra"]]
  )
)

outalltmp <- outall[, c(1:5, 12:14)]
colnames(outalltmp) <- c("Outcome/Subgroup", "Model", rep(c("No", "Yes", "p-value"), 2))

write.xlsx(outalltmp, paste0("./output/tabs/outcovid_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "RASi" = 3, "MRA" = 3)
names(myHeader) <- c(" ", " ", "RASi", "MRA")

footnote(mykable(outalltmp,
  fontsize = 6,
  caption = "Outcome Covid-19",
  longtable = TRUE
) %>%
  landscape() %>%
  add_header_above(myHeader),
general = c(
  "Adj = adjusted for variables indicated in baseline table.",
  "Adj IPW = adjusted for variables indicated in baseline table and using inverse probabilty weights for RASi and MRA respectively."
)
)
```

```{r orplotrasi, cache=cacheon, dependeson = "ortab", fig.cap="Forestplot Association RASi vs Covid-19"}
cextext <- 0.8

outforestor <- outrasi %>%
  filter(Model == "Adj IPW OR (95% CI)" &
    modname %in% c("All", "HF", "Hypertension", "Kidney disease", "IHD", "Diabetes", "Stockholm"))


par(mar = c(4, 11, 1, 2) + 0.2)
plot(rev(outforestor$logor), 1:nrow(outforestor),
  xlab = "",
  xlim = c(
    log(.6),
    log(1.2)
  ),
  ylim = c(1, nrow(outforestor) + 1),
  axes = FALSE,
  ylab = NA,
  cex.lab = 1.1,
  main = NA,
  cex = 2,
  type = "p",
  pch = 22,
  bg = global_kicols[1],
  col = global_kicols[1]
)


for (i in 1:nrow(outforestor)) {
  matplot(c(rev(outforestor$loglci)[i], rev(outforestor$loguci)[i]), c(i, i),
    type = "l", add = TRUE, col = global_kicols[1], cex = 2
  )
}
matplot(c(0, 0), c(-1, nrow(outforestor) + 0.5), type = "l", lty = 3, add = TRUE, col = "black")

axis(1,
  cex.axis = cextext, at = log(seq(0.6, 1.2, 0.1)),
  labels = c(0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2)
)

axis(2,
  at = 1:nrow(outforestor), labels = rev(outforestor$modname),
  cex.axis = cextext, tick = FALSE, las = 2, line = 10, hadj = 0
)

axis(2,
  at = 1:(nrow(outforestor) + 1),
  labels = c(rev(outforestor$Yes), "Odds Ratio (95% CI)"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 2, hadj = 0.5
)

axis(1,
  at = 0.01, cex.axis = cextext,
  labels = "RASi better         No RASi better", line = 1, tick = FALSE
)
```

```{r orplotmra, cache=cacheon, dependeson = "ortab", fig.cap="Forestplot Association MRA vs Covid-19"}
cextext <- 0.8

outforestor <- outmra %>%
  filter(Model == "Adj IPW OR (95% CI)" &
    modname %in% c("All", "HF", "Hypertension", "Kidney disease", "IHD", "Diabetes", "Stockholm"))


par(mar = c(4, 11, 1, 2) + 0.2)
plot(rev(outforestor$logor), 1:nrow(outforestor),
  xlab = "",
  xlim = c(
    log(.6),
    log(1.2)
  ),
  ylim = c(1, nrow(outforestor) + 1),
  axes = FALSE,
  ylab = NA,
  cex.lab = 1.1,
  main = NA,
  cex = 2,
  type = "p",
  pch = 22,
  bg = global_kicols[1],
  col = global_kicols[1]
)


for (i in 1:nrow(outforestor)) {
  matplot(c(rev(outforestor$loglci)[i], rev(outforestor$loguci)[i]), c(i, i),
    type = "l", add = TRUE, col = global_kicols[1], cex = 2
  )
}
matplot(c(0, 0), c(-1, nrow(outforestor) + 0.5), type = "l", lty = 3, add = TRUE, col = "black")

axis(1,
  cex.axis = cextext, at = log(seq(0.6, 1.2, 0.1)),
  labels = c(0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2)
)

axis(2,
  at = 1:nrow(outforestor), labels = rev(outforestor$modname),
  cex.axis = cextext, tick = FALSE, las = 2, line = 10, hadj = 0
)

axis(2,
  at = 1:(nrow(outforestor) + 1),
  labels = c(rev(outforestor$Yes), "Odds Ratio (95% CI)"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 2, hadj = 0.5
)

axis(1,
  at = 0.01, cex.axis = cextext,
  labels = "MRA better         No MRA better", line = 1, tick = FALSE
)
```
