```{r ortabdeath, cache=cacheon}

ordeathmy <- function(event, modvarsmy, data, modname, weight) {
  out <- data.frame(matrix(NA, ncol = 5, nrow = 4, 1))

  out[1, 1] <- modname

  colnames(out) <- c("Subgroup", "Model", "No", "Yes", "p-value")

  ns <- data %>%
    group_by(!!sym(modvarsmy[1])) %>%
    count(!!sym(event)) %>%
    mutate(
      p = n / sum(n),
      np = paste0(n, " (", dF(p * 100, dig = 2), "%)")
    ) %>%
    ungroup() %>%
    filter(!!sym(event) == "Yes")

  out[1, 2] <- "n (%) event"
  out[1, 3:4] <- ns %>% pull(np)


  # Crude
  mod <- glm(formula(paste(event, " == 'Yes' ~ ", modvarsmy[1])),
    data = data,
    family = binomial(link = "logit")
  )
  smod <- summary(mod)

  out[2, 2] <- "Crude OR (95% CI)"
  out[2, 3:5] <- cbind(
    "ref",
    paste0(
      dF(exp(smod$coefficients[2, 1]), dig = 2),
      " (", dF(exp(smod$coefficients[2, 1] - global_z05 * smod$coefficients[2, 2]), dig = 2),
      "-", dF(exp(smod$coefficients[2, 1] + global_z05 * smod$coefficients[2, 2]), dig = 2), ")"
    ),
    dF(smod$coefficients[2, 4], dig = 3, p = TRUE)
  )

  # Adj
  mod <- glm(formula(paste(event, " == 'Yes' ~ ", paste(modvarsmy, collapse = " + "))),
    data = data,
    family = binomial(link = "logit")
  )
  smod <- summary(mod)

  out[3, 2] <- "Adj OR (95% CI)"
  out[3, 3:5] <- cbind(
    "ref",
    paste0(
      dF(exp(smod$coefficients[2, 1]), dig = 2),
      " (", dF(exp(smod$coefficients[2, 1] - global_z05 * smod$coefficients[2, 2]), dig = 2),
      "-", dF(exp(smod$coefficients[2, 1] + global_z05 * smod$coefficients[2, 2]), dig = 2), ")"
    ),
    dF(smod$coefficients[2, 4], dig = 3, p = TRUE)
  )

  # Adj pS IPW

  mod <- glm(formula(paste(event, " == 'Yes' ~ ", paste(modvarsmy, collapse = " + "))),
    data = data,
    family = binomial(link = "logit"),
    weights = data %>% pull(!!weight)
  )

  smod <- jtools::get_robust_se(mod, type = "HC0")

  out[4, 2] <- "Adj IPW OR (95% CI)"
  out[4, 3:5] <- cbind(
    "ref",
    paste0(
      dF(exp(smod$coefs[2, 1]), dig = 2),
      " (", dF(exp(smod$coefs[2, 1] - global_z05 * smod$coefs[2, 2]), dig = 2),
      "-", dF(exp(smod$coefs[2, 1] + global_z05 * smod$coefs[2, 2]), dig = 2), ")"
    ),
    dF(smod$coefs[2, 4], dig = 3, p = TRUE)
  )

  return(out)
}
```

```{r ortabdeathrasimra, cache=cacheon, dependson="ortabdeath"}

# ACEi/ARB
out11 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & !is.na(sos_out_death30d)),
  modname = "All",
  weight = "weight_rasi"
)
out13 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_hf"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hf == "Yes" & !is.na(sos_out_death30d)),
  modname = "HF",
  weight = "weight_rasi"
)
out14 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_hypertension"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hypertension == "Yes" & !is.na(sos_out_death30d)),
  modname = "Hypertension",
  weight = "weight_rasi"
)
out15 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_renal"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_renal == "Yes" & !is.na(sos_out_death30d)),
  modname = "Kidney disease",
  weight = "weight_rasi"
)
out16 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_ihd"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_ihd == "Yes" & !is.na(sos_out_death30d)),
  modname = "IHD",
  weight = "weight_rasi"
)
out17 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_diabetes"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_diabetes == "Yes" & !is.na(sos_out_death30d)),
  modname = "Diabetes",
  weight = "weight_rasi"
)
out18 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasi", "sos_ddr_mra", modvarsns[!modvarsns %in% "scb_region_stockholm"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & scb_region_stockholm == "Yes" & !is.na(sos_out_death30d)),
  modname = "Stockholm",
  weight = "weight_rasi"
)

# MRA
out21 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_mra", "sos_ddr_rasi", modvarsns),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & !is.na(sos_out_death30d)),
  modname = "All",
  weight = "weight_mra"
)
out23 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_mra", "sos_ddr_rasi", modvarsns[!modvarsns %in% "sos_com_hf"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hf == "Yes" & !is.na(sos_out_death30d)),
  modname = "HF",
  weight = "weight_mra"
)
out24 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_mra", "sos_ddr_rasi", modvarsns[!modvarsns %in% "sos_com_hypertension"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hypertension == "Yes" & !is.na(sos_out_death30d)),
  modname = "Hypertension",
  weight = "weight_mra"
)
out25 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_mra", "sos_ddr_rasi", modvarsns[!modvarsns %in% "sos_com_renal"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_renal == "Yes" & !is.na(sos_out_death30d)),
  modname = "Kidney disease",
  weight = "weight_mra"
)
out26 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_mra", "sos_ddr_rasi", modvarsns[!modvarsns %in% "sos_com_ihd"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_ihd == "Yes" & !is.na(sos_out_death30d)),
  modname = "IHD",
  weight = "weight_mra"
)
out27 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_mra", "sos_ddr_rasi", modvarsns[!modvarsns %in% "sos_com_diabetes"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_diabetes == "Yes" & !is.na(sos_out_death30d)),
  modname = "Diabetes",
  weight = "weight_mra"
)
out28 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_mra", "sos_ddr_rasi", modvarsns[!modvarsns %in% "scb_region_stockholm"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & scb_region_stockholm == "Yes" & !is.na(sos_out_death30d)),
  modname = "Stockholm",
  weight = "weight_mra"
)

outall <- cbind(
  outrasi <- rbind(
    out11, out13, out14,
    out15, out16, out17,
    out18
  ),
  outmra <- rbind(
    out21, out23, out24,
    out25, out26, out27,
    out28
  )
)

outalltmp <- outall[, c(1:5, 8:10)]
colnames(outalltmp) <- c("Subgroup", "Model", rep(c("No", "Yes", "p-value"), 2))

write.xlsx(outalltmp, paste0("./output/tabs/death30daftercovid_rasimra_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "ACEi/ARB" = 3, "MRA" = 3)
names(myHeader) <- c(" ", " ", "ACEi/ARB", "MRA")

footnote(mykable(outalltmp,
  fontsize = 6,
  caption = "All-cause mortality within 30 days after confirmed Covid-19 ACEi/ARB and MRA",
  longtable = TRUE
) %>%
  landscape() %>%
  add_header_above(myHeader),
general = c(
  "Adj = adjusted for variables indicated in baseline table.",
  "Adj IPW = adjusted for variables indicated in baseline table and using inverse probabilty weights for ACEi/ARB and MRA respectively."
)
)
```

```{r ortabdeathrasimra2, cache=cacheon, dependson="ortabdeath"}

# ACEi
out11 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_acei", "sos_ddr_mra", modvarsns),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "All",
  weight = "weight_acei"
)
out13 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_acei", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_hf"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hf == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "HF",
  weight = "weight_acei"
)
out14 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_acei", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_hypertension"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hypertension == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "Hypertension",
  weight = "weight_acei"
)
out15 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_acei", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_renal"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_renal == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "Kidney disease",
  weight = "weight_acei"
)
out16 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_acei", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_ihd"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_ihd == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "IHD",
  weight = "weight_acei"
)
out17 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_acei", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_diabetes"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_diabetes == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "Diabetes",
  weight = "weight_acei"
)
out18 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_acei", "sos_ddr_mra", modvarsns[!modvarsns %in% "scb_region_stockholm"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & scb_region_stockholm == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "Stockholm",
  weight = "weight_acei"
)

# ARB
out21 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_arb", "sos_ddr_mra", modvarsns),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "All",
  weight = "weight_arb"
)
out23 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_arb", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_hf"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hf == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "HF",
  weight = "weight_arb"
)
out24 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_arb", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_hypertension"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hypertension == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "Hypertension",
  weight = "weight_arb"
)
out25 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_arb", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_renal"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_renal == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "Kidney disease",
  weight = "weight_arb"
)
out26 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_arb", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_ihd"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_ihd == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "IHD",
  weight = "weight_arb"
)
out27 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_arb", "sos_ddr_mra", modvarsns[!modvarsns %in% "sos_com_diabetes"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_diabetes == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "Diabetes",
  weight = "weight_arb"
)
out28 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_arb", "sos_ddr_mra", modvarsns[!modvarsns %in% "scb_region_stockholm"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & scb_region_stockholm == "Yes" & 
                          !(sos_ddr_acei == "Yes" & sos_ddr_arb == "Yes") & !is.na(sos_out_death30d)),
  modname = "Stockholm",
  weight = "weight_arb"
)

# ACEi/ARB + MRA
out31 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasimra", modvarsns),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & !is.na(sos_out_death30d)),
  modname = "All",
  weight = "weight_rasimra"
)
out33 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasimra", modvarsns[!modvarsns %in% "sos_com_hf"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hf == "Yes" & !is.na(sos_out_death30d)),
  modname = "HF",
  weight = "weight_rasimra"
)
out34 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasimra", modvarsns[!modvarsns %in% "sos_com_hypertension"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_hypertension == "Yes" & !is.na(sos_out_death30d)),
  modname = "Hypertension",
  weight = "weight_rasimra"
)
out35 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasimra", modvarsns[!modvarsns %in% "sos_com_renal"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_renal == "Yes" & !is.na(sos_out_death30d)),
  modname = "Kidney disease",
  weight = "weight_rasimra"
)
out36 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasimra", modvarsns[!modvarsns %in% "sos_com_ihd"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_ihd == "Yes" & !is.na(sos_out_death30d)),
  modname = "IHD",
  weight = "weight_rasimra"
)
out37 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasimra", modvarsns[!modvarsns %in% "sos_com_diabetes"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & sos_com_diabetes == "Yes" & !is.na(sos_out_death30d)),
  modname = "Diabetes",
  weight = "weight_rasimra"
)
out38 <- ordeathmy(
  event = "sos_out_death30d",
  modvarsmy = c("sos_ddr_rasimra", modvarsns[!modvarsns %in% "scb_region_stockholm"]),
  data = pop %>% filter(sos_covidconfirmed == "Yes" & scb_region_stockholm == "Yes" & !is.na(sos_out_death30d)),
  modname = "Stockholm",
  weight = "weight_rasimra"
)

outall <- cbind(
  outacei <- rbind(
    out11, out13, out14,
    out15, out16, out17,
    out18
  ),
  outarb <- rbind(
    out21, out23, out24,
    out25, out26, out27,
    out28
  ),
  outrasimra <- rbind(
    out31, out33, out34,
    out35, out36, out37,
    out38
  )
)

outalltmp <- outall[, c(1:5, 8:10, 13:15)]
colnames(outalltmp) <- c("Subgroup", "Model", rep(c("No", "Yes", "p-value"), 3))

write.xlsx(outalltmp, paste0("./output/tabs/death30daftercovid_rasimra2_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "ACEi" = 3, "ARB" = 3, "ACEi/ARB + MRA" = 3)
names(myHeader) <- c(" ", " ", "ACEi", "ARB", "ACEi/ARB + MRA")

footnote(mykable(outalltmp,
  fontsize = 6,
  caption = "All-cause mortality within 30 days after confirmed Covid-19 ACEi, ARB and ACEi/ARB + MRA",
  longtable = TRUE
) %>%
  landscape() %>%
  add_header_above(myHeader),
general = c(
  "Adj = adjusted for variables indicated in baseline table.",
  "Adj IPW = adjusted for variables indicated in baseline table and using inverse probabilty weights for ACEi, ARB and ACEi/ARB+MRA respectively."
)
)
```
