```{r tab1, cache=cacheon}

tab1func <- function(data, title) {
  tab1_tmp <- CreateTableOne(
    vars = tabvars,
    strata = "sos_ddr_rasi",
    data = data
  )
  tab1 <- print(tab1_tmp,
    varLabels = TRUE, missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
    test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE,
    smd = TRUE
  )

  tab1m_tmp <- CreateTableOne(
    vars = tabvars,
    strata = "sos_ddr_mra",
    data = data
  )
  tab1m <- print(tab1m_tmp,
    varLabels = TRUE, missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
    test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE,
    smd = TRUE
  )

  tab1out <- as_tibble(cbind(
    rownames(tab1), tab1[, 6],
    tab1[, c(1:3, 5)],
    tab1m[, c(1:3, 5)]
  ),
  .name_repair = "universal"
  )

  tab1out <- tab1out %>%
    mutate(
      tmp_varsforfoot = ...1,
      ...1 = sub("  ", ". ", ...1),
      ...1 = sanitizeTextFunc(...1)
    )


  ## add fotnote stating which variables are used in adj models

  tab1out$...1 <- ifelse(stri_extract_first_words(tab1out$tmp_varsforfoot) %in% c(modvars, "sos_ddr_rasi", "sos_ddr_mra"),
    paste0(tab1out$...1, footnote_marker_symbol(1)), tab1out$...1
  )

  ## add fotnote for disp income

  tab1out$...1 <- ifelse(stri_extract_first_words(tab1out$tmp_varsforfoot) == "scb_dispincome_cat",
    paste0(tab1out$...1, footnote_marker_symbol(2)), tab1out$...1
  )

  tab1out <- tab1out %>% select(-tmp_varsforfoot)

  ## white space removed in kable function.
  ## fix in order to use escape = TRUE

  colnames(tab1out) <- sanitizeTextFunc(c(
    "Variables", "Missing (%)", rep(c("No", "Yes", "p-value", "SMD"), 2)
  ))

  write.xlsx(tab1out, paste0("./output/tabs/tab1_", title, "_", Sys.Date(), ".xlsx"), rowNames = FALSE)


  myHeader <- c(" " = 1, " " = 1, "RASi" = 4, "MRA" = 4)
  names(myHeader) <- c(" ", " ", "RASi", "MRA")


  footnote(
    mykable(tab1out,
      fontsize = 6,
      caption = paste0("Baseline characteristics - ", title),
      longtable = TRUE,
      escape = FALSE
    ) %>%
      landscape() %>%
      add_header_above(myHeader),
    general = c(
      "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Mann-Whitney U test.",
      "SMD = Standardized mean difference."
    ),
    symbol = c(
      "Included in the logistic/cox regression/propensity score models.",
      "Categorized according to tertiles."
    )
  )
}
```

```{r tab1all, cache=cacheon, dependeson = "tab1"}

tab1func(
  data = pop,
  title = "All"
)
```

```{r tab1covid, cache=cacheon, dependeson = "tab1"}

tab1func(
  data = pop %>% filter(sos_covidconfirmed == "Yes"),
  title = "Covid-19"
)
```
