```{r vennall, fig.cap="Venn diagram All observations"}
popvenn <- pop %>%
  count(sos_com_ihd, 
        sos_com_hf, 
        sos_com_diabetes, 
        sos_com_renal, 
        sos_com_hypertension)

venn.plot <- draw.quintuple.venn(
  area1 = popvenn %>% filter(sos_com_ihd == "Yes") %>% count(wt = n) %>% pull(n),
  area2 = popvenn %>% filter(sos_com_hf == "Yes") %>% count(wt = n) %>% pull(n),
  area3 = popvenn %>% filter(sos_com_diabetes == "Yes") %>% count(wt = n) %>% pull(n),
  area4 = popvenn %>% filter(sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  area5 = popvenn %>% filter(sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  # 2 way
  n12 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes") %>% count(wt = n) %>% pull(n),
  n13 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_diabetes == "Yes") %>% count(wt = n) %>% pull(n),
  n14 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n15 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n23 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_diabetes == "Yes") %>% count(wt = n) %>% pull(n),
  n24 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n25 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n34 = popvenn %>% filter(sos_com_diabetes == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n35 = popvenn %>% filter(sos_com_diabetes == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n45 = popvenn %>% filter(sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  # 3 way
  n123 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & sos_com_diabetes == "Yes") %>% count(wt = n) %>% pull(n),
  n124 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n125 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n134 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_diabetes == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n135 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_diabetes == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n145 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n234 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_diabetes == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n235 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_diabetes == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n245 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n345 = popvenn %>% filter(sos_com_diabetes == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  # 4 way
  n1234 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n1235 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n1245 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & 
                       sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n1345 = popvenn %>% filter(sos_com_ihd == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n2345 = popvenn %>% filter(sos_com_hf == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  # 5 way
  n12345 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  category = c("IHD", "HF", "Diabetes", "Kidney", "Hypertension"), 
  print.mode = "percent",
  sigdigs = 1
  )

grid.draw(venn.plot)
```

```{r vennraasi, fig.cap="Venn diagram of patients taking RAASi+ARNI"}
popvenn <- pop %>% filter(sos_ddr_raasiarni == "Yes") %>%
  count(sos_com_ihd, 
        sos_com_hf, 
        sos_com_diabetes, 
        sos_com_renal, 
        sos_com_hypertension)

venn.plot <- draw.quintuple.venn(
  area1 = popvenn %>% filter(sos_com_ihd == "Yes") %>% count(wt = n) %>% pull(n),
  area2 = popvenn %>% filter(sos_com_hf == "Yes") %>% count(wt = n) %>% pull(n),
  area3 = popvenn %>% filter(sos_com_diabetes == "Yes") %>% count(wt = n) %>% pull(n),
  area4 = popvenn %>% filter(sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  area5 = popvenn %>% filter(sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  # 2 way
  n12 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes") %>% count(wt = n) %>% pull(n),
  n13 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_diabetes == "Yes") %>% count(wt = n) %>% pull(n),
  n14 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n15 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n23 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_diabetes == "Yes") %>% count(wt = n) %>% pull(n),
  n24 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n25 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n34 = popvenn %>% filter(sos_com_diabetes == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n35 = popvenn %>% filter(sos_com_diabetes == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n45 = popvenn %>% filter(sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  # 3 way
  n123 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & sos_com_diabetes == "Yes") %>% count(wt = n) %>% pull(n),
  n124 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n125 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n134 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_diabetes == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n135 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_diabetes == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n145 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n234 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_diabetes == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n235 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_diabetes == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n245 = popvenn %>% filter(sos_com_hf == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  n345 = popvenn %>% filter(sos_com_diabetes == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  # 4 way
  n1234 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_renal == "Yes") %>% count(wt = n) %>% pull(n),
  n1235 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n1245 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & 
                       sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n1345 = popvenn %>% filter(sos_com_ihd == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  n2345 = popvenn %>% filter(sos_com_hf == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  # 5 way
  n12345 = popvenn %>% filter(sos_com_ihd == "Yes" & sos_com_hf == "Yes" & 
                       sos_com_diabetes == "Yes" & sos_com_renal == "Yes" & sos_com_hypertension == "Yes") %>% count(wt = n) %>% pull(n),
  
  category = c("IHD", "HF", "Diabetes", "Kidney", "Hypertension"), 
  print.mode = "percent",
  sigdigs = 1
  
  )

grid.draw(venn.plot)
```